#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# mint-kiosk-setup.sh — turn a Linux Mint (Cinnamon / X11) PC into a
# wall-panel kiosk that boots straight into the dashboard, fullscreen,
# no browser chrome, no screen blanking, and relaunches Chromium if it dies.
#
# Usage (run ON the Mint PC, as your normal user — NOT root):
#   bash mint-kiosk-setup.sh http://192.168.1.140:8081/living-room
#
# What it does:
#   1. Installs chromium + unclutter (cursor hider)
#   2. Disables Cinnamon screensaver, lock, and display power-off
#   3. Writes ~/.local/bin/dashboard-kiosk.sh (xset + relaunch loop)
#   4. Adds a Cinnamon autostart entry that runs it on login
#   5. Enables LightDM auto-login (so it boots to the desktop unattended)
#   6. Prints reboot instructions
#
# Undo:
#   rm ~/.config/autostart/dashboard-kiosk.desktop ~/.local/bin/dashboard-kiosk.sh
#   sudo rm /etc/lightdm/lightdm.conf.d/50-dashboard-autologin.conf
#   then reboot.
#
# Tested target: Linux Mint 21/22 Cinnamon (X11). Not for Wayland sessions.
# ──────────────────────────────────────────────────────────────
set -euo pipefail

# Living-room panel → living-room-dashboard container (port 8081). Pass a URL to override.
URL="${1:-http://192.168.1.140:8081/living-room}"

if [[ "$(id -u)" -eq 0 ]]; then
  echo "Run this as your normal user (it will sudo when it needs to), not as root." >&2
  exit 2
fi

USER_NAME="$(id -un)"
echo "▸ Setting up dashboard kiosk for user '$USER_NAME' → $URL"

# ── 1. Packages ────────────────────────────────────────────────
echo "▸ Installing chromium + unclutter…"
sudo apt-get update -qq
# Mint ships a real chromium .deb (no snap). Fall back to chromium-browser just in case.
sudo apt-get install -y unclutter x11-xserver-utils
if ! sudo apt-get install -y chromium 2>/dev/null; then
  sudo apt-get install -y chromium-browser
fi
# Resolve the chromium binary name once.
CHROME_BIN="$(command -v chromium || command -v chromium-browser || true)"
if [[ -z "$CHROME_BIN" ]]; then
  echo "ERROR: could not find a chromium binary after install." >&2
  exit 1
fi
echo "  → using $CHROME_BIN"

# ── 2. Kill Cinnamon screensaver / lock / display power-off ────
echo "▸ Disabling screensaver, lock, and display sleep…"
gsettings set org.cinnamon.desktop.screensaver lock-enabled false 2>/dev/null || true
gsettings set org.cinnamon.desktop.screensaver idle-activation-enabled false 2>/dev/null || true
gsettings set org.cinnamon.desktop.session idle-delay 0 2>/dev/null || true
gsettings set org.cinnamon.settings-daemon.plugins.power sleep-display-ac 0 2>/dev/null || true
gsettings set org.cinnamon.settings-daemon.plugins.power sleep-display-battery 0 2>/dev/null || true
gsettings set org.cinnamon.settings-daemon.plugins.power lid-close-ac-action 'nothing' 2>/dev/null || true

# ── 3. Kiosk launch script ─────────────────────────────────────
echo "▸ Writing ~/.local/bin/dashboard-kiosk.sh…"
mkdir -p "$HOME/.local/bin"
cat > "$HOME/.local/bin/dashboard-kiosk.sh" << EOF
#!/usr/bin/env bash
# Auto-generated by mint-kiosk-setup.sh — launches the dashboard fullscreen.
export DISPLAY=:0
URL="$URL"
CHROME_BIN="$CHROME_BIN"
PROFILE="\$HOME/.config/dashboard-chromium"

# Give the desktop + network a moment to come up.
sleep 6

# Kill X screen blanking + DPMS so the panel never sleeps.
xset s off || true
xset s noblank || true
xset -dpms || true

# Hide the mouse pointer when idle.
unclutter -idle 0.5 -root &

# Relaunch Chromium if it ever exits/crashes.
while true; do
  # Clear the "Chromium didn't shut down correctly / restore pages?" flags.
  PREFS="\$PROFILE/Default/Preferences"
  if [[ -f "\$PREFS" ]]; then
    sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' "\$PREFS" || true
    sed -i 's/"exit_type":"[^"]\+"/"exit_type":"Normal"/' "\$PREFS" || true
  fi

  "\$CHROME_BIN" \\
    --kiosk "\$URL" \\
    --user-data-dir="\$PROFILE" \\
    --noerrdialogs \\
    --disable-infobars \\
    --disable-session-crashed-bubble \\
    --disable-features=TranslateUI \\
    --no-first-run \\
    --check-for-update-interval=31536000 \\
    --overscroll-history-navigation=0 \\
    --disable-pinch \\
    --touch-events=enabled \\
    --autoplay-policy=no-user-gesture-required \\
    --password-store=basic

  sleep 3
done
EOF
chmod +x "$HOME/.local/bin/dashboard-kiosk.sh"

# ── 4. Autostart entry ─────────────────────────────────────────
echo "▸ Adding Cinnamon autostart entry…"
mkdir -p "$HOME/.config/autostart"
cat > "$HOME/.config/autostart/dashboard-kiosk.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Dashboard Kiosk
Comment=Launch the wall-panel dashboard fullscreen on login
Exec=$HOME/.local/bin/dashboard-kiosk.sh
X-GNOME-Autostart-enabled=true
Terminal=false
EOF

# ── 5. LightDM auto-login ──────────────────────────────────────
echo "▸ Enabling LightDM auto-login for '$USER_NAME'…"
sudo mkdir -p /etc/lightdm/lightdm.conf.d
sudo tee /etc/lightdm/lightdm.conf.d/50-dashboard-autologin.conf >/dev/null << EOF
[Seat:*]
autologin-user=$USER_NAME
autologin-user-timeout=0
EOF

echo
echo "✔ Kiosk configured."
echo "  Reboot to test:   sudo reboot"
echo "  The PC will auto-login and open $URL fullscreen."
echo "  To quit kiosk temporarily: press Ctrl+Alt+F2 for a TTY, or plug in a"
echo "  keyboard and press Alt+F4 (it will relaunch — disable the autostart"
echo "  entry in Menu → Startup Applications to stop it permanently)."
